"""Build fresh streams or repack a fixed unlabeled sequence."""

from __future__ import annotations

from collections import Counter
from collections.abc import Iterator, Mapping
from concurrent.futures import Executor, ProcessPoolExecutor, ThreadPoolExecutor, as_completed
from contextlib import closing
from dataclasses import dataclass, field
from functools import cache, partial
import itertools
import json
import math
from multiprocessing import get_context
import os
from pathlib import Path
import time

import msgpack
import numpy as np
import orjson
from tqdm import tqdm
import yaml

from pumit.ucpt.packing import PACKING_POLICY, CostModel, pack_samples, repack_samples, write_shard
from pumit.ucpt.sample_stream import _load_generation_globals, generate_sample

from ..mask_store import MASK_STORAGE, mask_shard_path, write_mask_shard
from .manifest import ALGORITHM, ensure_build_plan, report_path, sha256_bytes, sha256_file, write_report
from .metadata import SAMPLE_METADATA_CONTRACT, canonicalize_sample_metadata
from .prefetch import OrderedPrefetchIterator
from .resources import process_rss_bytes, sample_process_capacity


SHARD_THREADS = 8


@dataclass(frozen=True)
class ShardBuildRequest:
    """Inputs that determine one shard."""

    shard_id: int
    shard_rng: np.random.Generator = field(repr=False, compare=False)
    config_path: str
    cost_model: CostModel
    budget_ms: float
    label_budget_fraction: float
    batches_per_shard: int
    output_dir: str
    build_fingerprint: str
    source_stream: str | None
    n_total_records: int | None = None
    n_labeled_records: int | None = None
    sample_executor: Executor | None = field(default=None, repr=False, compare=False)
    sample_prefetch: int = 1


@cache
def _load_worker_globals(config_path: str):
    pipeline, pools, class_sampler = _load_generation_globals(config_path)
    return pipeline, pools, class_sampler


def _init_sample_worker(config_path: str) -> None:
    _load_worker_globals(config_path)


def _generate_valid_sample(
    rng: np.random.Generator,
    *,
    config_path: str,
    labeled: bool,
) -> dict:
    """Advance one sample RNG until generation returns a valid sample."""
    pipeline, pools, class_sampler = _load_worker_globals(config_path)
    while True:
        sample = generate_sample(pipeline, pools, class_sampler, rng, labeled)
        if sample is not None:
            return sample


def _sample_rngs(rng: np.random.Generator) -> Iterator[np.random.Generator]:
    """Yield one independent child RNG per final sample."""
    while True:
        yield rng.spawn(1)[0]


def _sample_iter(
    rng: np.random.Generator,
    config_path: str,
    labeled: bool,
    *,
    executor: Executor | None = None,
    max_inflight: int = 1,
) -> Iterator[dict]:
    """Yield valid samples, optionally generated by a bounded shared executor."""
    producer = partial(
        _generate_valid_sample,
        config_path=config_path,
        labeled=labeled,
    )
    if executor is not None:
        return OrderedPrefetchIterator(
            producer,
            executor=executor,
            max_inflight=max_inflight,
            inputs=_sample_rngs(rng),
        )

    def sequential() -> Iterator[dict]:
        for sample_rng in _sample_rngs(rng):
            yield producer(sample_rng)

    return sequential()


def generation_fingerprint(
    seed: int,
    batches_per_shard: int,
    budget_ms: float,
    label_budget_fraction: float,
    cost_model: dict,
    config: dict,
    *,
    source_meta_sha256: str | None,
) -> str:
    """Hash every declared input that determines shard bytes."""
    fingerprint_inputs = {
        'algorithm': ALGORITHM,
        'packing_policy': PACKING_POLICY,
        'seed': seed,
        'batches_per_shard': batches_per_shard,
        'budget_ms': budget_ms,
        'label_budget_fraction': label_budget_fraction,
        'cost_model': cost_model,
        'config': config,
        'source_meta_sha256': source_meta_sha256,
    }
    payload = orjson.dumps(
        fingerprint_inputs,
        option=orjson.OPT_SORT_KEYS | orjson.OPT_NON_STR_KEYS,
    )
    return sha256_bytes(payload)[:16]


def distributed_context(environ: Mapping[str, str] | None = None) -> tuple[int, int]:
    """Return ``(rank, world_size)`` for node-level shard partitioning."""
    environ = os.environ if environ is None else environ
    has_rank = 'RANK' in environ
    has_world_size = 'WORLD_SIZE' in environ
    if has_rank != has_world_size:
        raise RuntimeError('RANK and WORLD_SIZE must either both be set or both be absent')
    if not has_rank:
        return 0, 1

    rank = int(environ['RANK'])
    world_size = int(environ['WORLD_SIZE'])
    if world_size < 1:
        raise ValueError(f'WORLD_SIZE must be positive, got {world_size}')
    if not 0 <= rank < world_size:
        raise ValueError(f'RANK must be in [0, {world_size}), got {rank}')
    return rank, world_size


def partition_shard_ids(shard_ids: list[int], rank: int, world_size: int) -> list[int]:
    """Assign a stable strided subset of global shard IDs to one node."""
    if world_size < 1:
        raise ValueError(f'world_size must be positive, got {world_size}')
    if not 0 <= rank < world_size:
        raise ValueError(f'rank must be in [0, {world_size}), got {rank}')
    return shard_ids[rank::world_size]


def _flatten_samples(shard: dict) -> list[dict]:
    return [sample for batch in shard['batches'] for sample in batch['samples']]


def _is_source_labeled(sample: dict) -> bool:
    """Recognize the current explicit flag and both obsolete labeled schemas."""
    if 'labeled' in sample:
        if not isinstance(sample['labeled'], bool):
            raise ValueError(f"sample labeled flag must be boolean: {sample['labeled']!r}")
        return sample['labeled']
    return 'classes' in sample or 'label_classes' in sample


def _upgrade_source_unlabeled(sample: dict) -> dict:
    """Add the explicit kind flag while preserving reusable augmentation state."""
    if _is_source_labeled(sample):
        raise ValueError('cannot upgrade a labeled source sample as unlabeled')
    if sample.get('labeled') is False:
        return sample
    return {**sample, 'labeled': False}


def _msgpack_equal(left, right) -> bool:
    """Compare decoded MessagePack values while treating matching NaNs as equal."""
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        return left.keys() == right.keys() and all(
            _msgpack_equal(left[key], right[key]) for key in left
        )
    if isinstance(left, list):
        return len(left) == len(right) and all(
            _msgpack_equal(a, b) for a, b in zip(left, right, strict=True)
        )
    if isinstance(left, float) and math.isnan(left):
        return math.isnan(right)
    return left == right


def _histogram(values: list[int]) -> dict[int, int]:
    return dict(sorted(Counter(values).items()))


def _load_repack_source(source_path: Path) -> tuple[bytes, list[dict], int]:
    """Load the complete ordered unlabeled stream and count discarded labeled samples."""
    source_bytes = source_path.read_bytes()
    source_shard = msgpack.unpackb(source_bytes, raw=False)
    source_samples = _flatten_samples(source_shard)
    unlabeled = [
        canonicalize_sample_metadata(_upgrade_source_unlabeled(sample))[0]
        for sample in source_samples
        if not _is_source_labeled(sample)
    ]
    return source_bytes, unlabeled, len(source_samples) - len(unlabeled)


def _validate_batches(batches: list[dict], cost_model: CostModel, budget_ms: float, shard_id: int) -> dict:
    batch_costs: list[float] = []
    batch_sizes: list[int] = []
    labeled_per_batch: list[int] = []
    unlabeled_per_batch: list[int] = []
    for batch_index, batch in enumerate(batches):
        n_labeled = sum(sample['labeled'] for sample in batch['samples'])
        n_unlabeled = len(batch['samples']) - n_labeled
        if n_labeled < 1 or n_unlabeled < 1:
            raise ValueError(
                f'shard {shard_id} batch {batch_index}: floor violation ({n_labeled=}, {n_unlabeled=})'
            )
        batch_cost = sum(cost_model.sample_cost(sample) for sample in batch['samples'])
        labeled_costs = [
            cost_model.sample_cost(sample)
            for sample in batch['samples']
            if sample['labeled']
        ]
        unlabeled_costs = [
            cost_model.sample_cost(sample)
            for sample in batch['samples']
            if not sample['labeled']
        ]
        overshoot_bound = budget_ms + max(labeled_costs) + max(unlabeled_costs)
        if batch_cost > overshoot_bound + 1e-6:
            raise ValueError(
                f'shard {shard_id} batch {batch_index}: cost {batch_cost} exceeds nearest '
                f'rounding bound {overshoot_bound}'
            )
        batch_costs.append(batch_cost)
        batch_sizes.append(len(batch['samples']))
        labeled_per_batch.append(n_labeled)
        unlabeled_per_batch.append(n_unlabeled)
    return {
        'batch_cost_mean_ms': float(np.mean(batch_costs)),
        'batch_cost_p95_ms': float(np.percentile(batch_costs, 95)),
        'batch_cost_max_ms': float(max(batch_costs)),
        'batch_size_histogram': _histogram(batch_sizes),
        'labeled_per_batch_histogram': _histogram(labeled_per_batch),
        'unlabeled_per_batch_histogram': _histogram(unlabeled_per_batch),
    }


def build_one_shard(request: ShardBuildRequest) -> dict:
    """Build one fresh or repacked shard and its report."""
    output_dir = Path(request.output_dir)
    output_path = output_dir / f'shard_{request.shard_id:05d}.msgpack'
    mask_path = mask_shard_path(output_dir, request.shard_id)
    if (
        output_path.exists()
        or mask_path.exists()
        or report_path(output_dir, request.shard_id).exists()
    ):
        raise FileExistsError(f'shard output already exists: {request.shard_id}')
    print(f'[ucpt] shard {request.shard_id}: start', flush=True)

    n_total_records = request.n_total_records
    n_labeled_records = request.n_labeled_records
    if n_total_records is None or n_labeled_records is None:
        _, pools, _ = _load_worker_globals(request.config_path)
        (records_all, _), (records_labeled, _) = pools
        n_total_records = len(records_all)
        n_labeled_records = len(records_labeled)
    source_bytes = None
    reusable_unlabeled: list[dict] = []
    old_labeled_samples = 0
    if request.source_stream is not None:
        source_path = Path(request.source_stream) / f'shard_{request.shard_id:05d}.msgpack'
        source_bytes, reusable_unlabeled, old_labeled_samples = _load_repack_source(source_path)
    old_unlabeled_samples = len(reusable_unlabeled)
    old_unlabeled_patches = sum(sample['n_patches'] for sample in reusable_unlabeled)

    labeled_rng, unlabeled_rng = request.shard_rng.spawn(2)
    labeled_iter = _sample_iter(
        labeled_rng,
        request.config_path,
        True,
        executor=request.sample_executor,
        max_inflight=request.sample_prefetch,
    )
    generated_unlabeled_iter = None
    if request.source_stream is None:
        generated_unlabeled_iter = _sample_iter(
            unlabeled_rng,
            request.config_path,
            False,
        )
        unlabeled_iter = itertools.chain(reusable_unlabeled, generated_unlabeled_iter)
    else:
        unlabeled_iter = None
    batches = []
    shard_start = time.monotonic()
    last_progress = shard_start
    with closing(labeled_iter):
        if request.source_stream is not None:
            packed_batches = repack_samples(
                labeled_iter=labeled_iter,
                unlabeled_samples=reusable_unlabeled,
                batches=request.batches_per_shard,
                budget_ms=request.budget_ms,
                label_budget_fraction=request.label_budget_fraction,
                cost_model=request.cost_model,
            )
        else:
            packed_batches = itertools.islice(
                pack_samples(
                    labeled_iter=labeled_iter,
                    unlabeled_iter=unlabeled_iter,
                    budget_ms=request.budget_ms,
                    label_budget_fraction=request.label_budget_fraction,
                    cost_model=request.cost_model,
                ),
                request.batches_per_shard,
            )
        for batch in packed_batches:
            batches.append(batch)
            now = time.monotonic()
            if len(batches) == 1 or len(batches) == request.batches_per_shard or now - last_progress >= 60:
                elapsed = now - shard_start
                rate = len(batches) / elapsed
                eta = (request.batches_per_shard - len(batches)) / rate
                print(
                    f'[ucpt] shard {request.shard_id}: {len(batches)}/{request.batches_per_shard} batches, '
                    f'{rate:.3f} batches/s, ETA {eta / 60:.1f} min',
                    flush=True,
                )
                last_progress = now
    if generated_unlabeled_iter is not None:
        generated_unlabeled_iter.close()
    if len(batches) != request.batches_per_shard:
        raise ValueError(
            f'shard {request.shard_id}: produced {len(batches)} batches, expected {request.batches_per_shard}'
        )
    batch_stats = _validate_batches(
        batches,
        request.cost_model,
        request.budget_ms,
        request.shard_id,
    )

    output_samples = [sample for batch in batches for sample in batch['samples']]
    output_labeled = [sample for sample in output_samples if sample['labeled']]
    output_unlabeled = [sample for sample in output_samples if not sample['labeled']]
    if request.source_stream is not None:
        if not _msgpack_equal(output_unlabeled, reusable_unlabeled):
            raise ValueError(f'shard {request.shard_id}: reusable unlabeled sequence diverged')
    used_old_unlabeled_samples = min(len(output_unlabeled), len(reusable_unlabeled))
    if not _msgpack_equal(
        output_unlabeled[:used_old_unlabeled_samples],
        reusable_unlabeled[:used_old_unlabeled_samples],
    ):
        raise ValueError(f'shard {request.shard_id}: reusable unlabeled prefix diverged')

    generated_unlabeled = output_unlabeled[used_old_unlabeled_samples:]
    used_old_unlabeled = output_unlabeled[:used_old_unlabeled_samples]
    used_old_unlabeled_patches = sum(sample['n_patches'] for sample in used_old_unlabeled)
    generated_labeled_patches = sum(sample['n_patches'] for sample in output_labeled)
    generated_unlabeled_patches = sum(sample['n_patches'] for sample in generated_unlabeled)

    used_old_labeled_samples = 0
    generated_labeled_samples = len(output_labeled)
    if request.source_stream is not None:
        generated_unlabeled = []

    mask_stats = write_mask_shard(batches, mask_path)
    write_shard(batches, output_path)
    report = {
        'build_fingerprint': request.build_fingerprint,
        'shard_id': request.shard_id,
        'source_sha256': sha256_bytes(source_bytes) if source_bytes is not None else None,
        'output_sha256': sha256_file(output_path),
        'old_labeled_samples': old_labeled_samples,
        'old_unlabeled_samples': old_unlabeled_samples,
        'used_old_labeled_samples': used_old_labeled_samples,
        'used_old_unlabeled_samples': used_old_unlabeled_samples,
        'dropped_old_unlabeled_samples': old_unlabeled_samples - used_old_unlabeled_samples,
        'generated_labeled_samples': generated_labeled_samples,
        'generated_unlabeled_samples': len(generated_unlabeled),
        'old_unlabeled_patches': old_unlabeled_patches,
        'used_old_unlabeled_patches': used_old_unlabeled_patches,
        'dropped_old_unlabeled_patches': old_unlabeled_patches - used_old_unlabeled_patches,
        'generated_labeled_patches': generated_labeled_patches,
        'generated_unlabeled_patches': generated_unlabeled_patches,
        'logical_latent_rows': used_old_unlabeled_patches + generated_unlabeled_patches,
        'n_total_records': n_total_records,
        'n_labeled_records': n_labeled_records,
        'new_labeled_samples': len(output_labeled),
        'new_unlabeled_samples': len(output_unlabeled),
        'new_labeled_sample_fraction': len(output_labeled) / len(output_samples),
        'sample_metadata_contract': SAMPLE_METADATA_CONTRACT,
        'mask_storage': MASK_STORAGE,
        'mask_sha256': sha256_file(mask_path),
        **mask_stats,
        **batch_stats,
    }
    write_report(output_dir, report)
    return report


def _completed_shard(stream_dir: Path, shard_id: int, fingerprint: str) -> bool:
    shard_path = stream_dir / f'shard_{shard_id:05d}.msgpack'
    mask_path = mask_shard_path(stream_dir, shard_id)
    sidecar_path = report_path(stream_dir, shard_id)
    paths = (shard_path, mask_path, sidecar_path)
    if not any(path.exists() for path in paths):
        return False
    if not all(path.exists() for path in paths):
        raise RuntimeError(f'shard {shard_id} has a partial output; remove it before resuming')
    report = json.loads(sidecar_path.read_text())
    if report['build_fingerprint'] != fingerprint:
        raise RuntimeError(f'shard {shard_id} report fingerprint mismatch')
    if report['output_sha256'] != sha256_file(shard_path):
        raise RuntimeError(f'shard {shard_id} output hash differs from its report')
    if report['mask_sha256'] != sha256_file(mask_path):
        raise RuntimeError(f'shard {shard_id} mask hash differs from its report')
    if report['mask_storage_bytes'] != mask_path.stat().st_size:
        raise RuntimeError(f'shard {shard_id} mask size differs from its report')
    if report['mask_storage'] != MASK_STORAGE:
        raise RuntimeError(f'shard {shard_id} uses unsupported mask storage')
    if report.get('sample_metadata_contract') != SAMPLE_METADATA_CONTRACT:
        raise RuntimeError(f'shard {shard_id} uses obsolete sample metadata')
    return True


def _load_cost_model(
    cost_model_path: str | Path | None,
    use_default_cost_model: bool,
) -> tuple[CostModel, str]:
    if (cost_model_path is not None) == use_default_cost_model:
        raise ValueError('provide exactly one of cost_model_path or use_default_cost_model=True')
    if cost_model_path is not None:
        path = str(Path(cost_model_path).resolve())
        return CostModel.from_file(path), path
    return CostModel.default(), 'embedded-default'


def build_stream(
    *,
    config_path: str | Path,
    shards: int,
    shard_offset: int,
    output_dir: str | Path,
    seed: int,
    batches_per_shard: int,
    budget_ms: float,
    label_budget_fraction: float,
    cost_model_path: str | Path | None,
    use_default_cost_model: bool,
    source_stream: str | Path | None,
    shard_workers: int = SHARD_THREADS,
    sample_workers: int | None = None,
    sample_prefetch_factor: int = 8,
    force: bool = False,
) -> None:
    """Build a partition of independently addressed stream shards."""
    if shards < 1:
        raise ValueError(f'shards must be positive, got {shards}')
    if shard_offset < 0:
        raise ValueError(f'shard_offset must be non-negative, got {shard_offset}')
    if seed < 0:
        raise ValueError(f'seed must be non-negative, got {seed}')
    if batches_per_shard < 1:
        raise ValueError(f'batches_per_shard must be positive, got {batches_per_shard}')
    if budget_ms <= 0:
        raise ValueError(f'budget_ms must be positive, got {budget_ms}')
    if not 0 <= label_budget_fraction <= 1:
        raise ValueError(f'label_budget_fraction must be in [0, 1], got {label_budget_fraction}')
    if shard_workers < 1:
        raise ValueError(f'shard_workers must be positive, got {shard_workers}')
    if sample_workers is not None and sample_workers < 1:
        raise ValueError(f'sample_workers must be positive, got {sample_workers}')
    if sample_prefetch_factor < 1:
        raise ValueError(f'sample_prefetch_factor must be positive, got {sample_prefetch_factor}')

    config_path = str(Path(config_path).resolve())
    output_dir = Path(output_dir).resolve()
    generation_config = yaml.safe_load(Path(config_path).read_text())
    cost_model, cost_model_source = _load_cost_model(cost_model_path, use_default_cost_model)
    cost_model_fit = cost_model.as_fit_result()

    source_meta_sha256 = None
    source_dir = None
    if source_stream is not None:
        source_dir = Path(source_stream).resolve()
        source_meta_bytes = (source_dir / 'meta.yaml').read_bytes()
        source_meta_sha256 = sha256_bytes(source_meta_bytes)
        source_meta = yaml.safe_load(source_meta_bytes)
        if not source_meta.get('stream_complete'):
            raise ValueError(f'source stream is not finalized: {source_dir}')
        if generation_config != source_meta['config']:
            raise ValueError('repack requires the source generation config to remain unchanged')
        # Reusable unlabeled samples are self-contained. Fresh labeled generation may use an updated data pool; per-shard reports
        # and finalization verify that all workers observe one consistent current pool.

    fingerprint = generation_fingerprint(
        seed,
        batches_per_shard,
        budget_ms,
        label_budget_fraction,
        cost_model_fit,
        generation_config,
        source_meta_sha256=source_meta_sha256,
    )
    plan = {
        'fingerprint': fingerprint,
        'algorithm': ALGORITHM,
        'packing_policy': PACKING_POLICY,
        'seed': seed,
        'batches_per_shard': batches_per_shard,
        'budget_ms': budget_ms,
        'label_budget_fraction': label_budget_fraction,
        'cost_model_source': cost_model_source,
        'cost_model': cost_model_fit,
        'config': generation_config,
        'source_stream': str(source_dir) if source_dir is not None else None,
        'source_meta_sha256': source_meta_sha256,
    }
    ensure_build_plan(output_dir, plan)

    global_target_ids = list(range(shard_offset, shard_offset + shards))
    stream_rng = np.random.default_rng(seed).spawn(1)[0]
    shard_rngs = stream_rng.spawn(shard_offset + shards)
    if source_dir is not None:
        source_meta = yaml.safe_load((source_dir / 'meta.yaml').read_text())
        if global_target_ids[-1] >= source_meta['n_shards']:
            raise ValueError(
                f'target shard {global_target_ids[-1]} exceeds source range [0, {source_meta["n_shards"]})'
            )
    rank, world_size = distributed_context()
    target_ids = partition_shard_ids(global_target_ids, rank, world_size)
    if force:
        for shard_id in target_ids:
            (output_dir / f'shard_{shard_id:05d}.msgpack').unlink(missing_ok=True)
            mask_shard_path(output_dir, shard_id).unlink(missing_ok=True)
            report_path(output_dir, shard_id).unlink(missing_ok=True)

    completed = {
        shard_id
        for shard_id in target_ids
        if _completed_shard(output_dir, shard_id, fingerprint)
    }
    pending = [shard_id for shard_id in target_ids if shard_id not in completed]

    print(
        f'[ucpt] rank {rank}/{world_size} owns {len(target_ids)}/{len(global_target_ids)} shard IDs '
        f'from [{shard_offset}, {shard_offset + shards}); {len(completed)} complete'
    )
    if not pending:
        return

    _, pools, _ = _load_worker_globals(config_path)
    (records_all, _), (records_labeled, _) = pools
    n_total_records = len(records_all)
    n_labeled_records = len(records_labeled)
    worker_rss = process_rss_bytes()
    if sample_workers is None:
        sample_workers, cpu_capacity, memory_capacity = sample_process_capacity(worker_rss)
        print(
            f'[ucpt] sample process capacity: selected={sample_workers}, cpu={cpu_capacity}, '
            f'memory={memory_capacity}, measured_worker_rss={worker_rss / 2**30:.2f} GiB'
        )
    active_shards = min(shard_workers, len(pending))
    workers_per_shard = math.ceil(sample_workers / active_shards)
    sample_prefetch = sample_prefetch_factor * workers_per_shard
    print(
        f'[ucpt] using {active_shards} shard threads, {sample_workers} shared sample processes, '
        f'prefetch factor {sample_prefetch_factor} '
        f'({sample_prefetch} in-flight samples/shard)'
    )

    start = time.time()
    context = get_context('spawn')
    with ProcessPoolExecutor(
        max_workers=sample_workers,
        mp_context=context,
        initializer=_init_sample_worker,
        initargs=(config_path,),
    ) as sample_pool:
        requests = [
            ShardBuildRequest(
                shard_id=shard_id,
                shard_rng=shard_rngs[shard_id],
                config_path=config_path,
                cost_model=cost_model,
                budget_ms=budget_ms,
                label_budget_fraction=label_budget_fraction,
                batches_per_shard=batches_per_shard,
                output_dir=str(output_dir),
                build_fingerprint=fingerprint,
                source_stream=str(source_dir) if source_dir is not None else None,
                n_total_records=n_total_records,
                n_labeled_records=n_labeled_records,
                sample_executor=sample_pool,
                sample_prefetch=sample_prefetch,
            )
            for shard_id in pending
        ]
        with ThreadPoolExecutor(max_workers=active_shards, thread_name_prefix='shard-build') as shard_pool:
            request_iter = iter(requests)
            futures = {
                shard_pool.submit(build_one_shard, request)
                for request in itertools.islice(request_iter, active_shards)
            }
            progress = tqdm(total=len(requests), desc='Shards', unit='shard')
            try:
                while futures:
                    future = next(as_completed(futures))
                    futures.remove(future)
                    future.result()
                    progress.update()
                    if request := next(request_iter, None):
                        futures.add(shard_pool.submit(build_one_shard, request))
            except BaseException:
                for future in futures:
                    future.cancel()
                raise
            finally:
                progress.close()
    print(f'[ucpt] built {len(pending)} shards in {time.time() - start:.1f}s')
